version: 2

models:
  - name: flight
    columns:
      - name: Date
        tests:
          - accepted_types:
              types: [STRING]
      - name: Code
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Number
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Origin
        tests:
          - accepted_types:
              types: [STRING]
      - name: Destination
        tests:
          - accepted_types:
              types: [STRING]
      - name: Departure Time
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Departure Delay
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Arrival Time
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Arrival Delay
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Flight Time
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Distance
        tests:
          - accepted_types:
              types: [INTEGER]
      - name: Record ID
        tests:
          - accepted_types:
              types: [INTEGER]
