version: 2

models:
  - name: flights_data_mart
    columns:
      - name: Date
      - name: Code
      - name: Number
      - name: Origin
      - name: Destination
      - name: Departure Time
      - name: Departure Delay
      - name: Arrival Time
      - name: Arrival Delay
      - name: Flight Time
      - name: Distance
      - name: Record ID
