version: 2

models:
  - name: flights_data_mart
    columns:
      - name: Date
        tests:
          - not_null
      - name: Code
        tests:
          - not_null
      - name: Number
        tests:
          - not_null
      - name: Origin
        tests:
          - not_null
      - name: Destination
        tests:
          - not_null
